### ISSUE TITLE
What does this actually count?

### ISSUE THREAD

**Issue by MattWilcox** [szenario-fordesigners/spacecontrol#7]
"Webspace" in relation to what folders? I assume this is also not including the space taken by the database?

**Comment by smonist** [comment]
Hey Matt,
we calculate webspace in relation to the Craft installation root folder. We pull the path from the 'CRAFT_BASE_PATH' environment variable.
Database space is not taken into account (yet), mostly because it is usally not limited by hosting providers. This could be an interesting feature for people who host on a root server :)

**Comment by MattWilcox** [comment]
Thanks for the info! Yeah, we host on a VPS generally, so the DB (and potentially backups location) are things we'd also want to be counting.

**Comment by smonist** [comment]
Hey Matt,

we just added support to include database size in used space with the latest [1.1.0 release](https://github.com/szenario-fordesigners/spacecontrol/releases/tag/1.1.0). Feel free to try it and report back to us :)

**Comment by MattWilcox** [comment]
Great stuff thanks, have let the team know!
